.vscode/settings.json, Makefile, include/minishell.h, src/main.c
=> [m_fix] : linking rosetta brew readline library & [m_feat] : handle SIGINT & SIGQUIT like bash

lib/libft/ft_strjoin.c, src/pipe/breed_process.c, src/pipe/check_validity.c, src/pipe/file_redirection.c, src/pipe/get_next_line.c, src/pipe/get_next_line_bonus.h, src/pipe/get_next_line_utils.c, src/pipe/get_params.c, src/pipe/handle_error.c, src/pipe/libft.h, src/pipe/parse_commend.c, src/pipe/pipe.h, src/pipe/pipe_main.c, src/pipe/string_utils.c, src/pipe/wait_info.c, src/pipe/waiting.c
change date of header later... 🤪
=> m_feat : basic pipe structure added

Makefile, include/minishell.h, lib/libft/ft_strdup.c, lib/libft/ft_strjoin.c, lib/libft/ft_strtrim.c, src/main.c, src/parse.c, src/parse_split.c
=> respect '"` and split by ;| draft & ft_strdup, ft_strjoin, ft_strtrim calloc and is_error

Makefile, include/minishell.h, src/main.c
make를 더 깔끔하게 만들어 보았읍니다... m1에서 잘 되는지 확인해주세요
클러스터에서는 잘됩니당
만약 안되면,,, c 헤더파일에서도 arch 기반으로 조건문 거는걸 찾아보겠읍니다.
+) m1 에서 arch 입력하면 arm64 뜨는거 맞죠? 맥북을 안가져와서 기억에 의존해서 넣었읍니다
=> m_feat : modify makefile to complie depends on arch

Makefile, include/minishell.h
M1 arm64 brew readline 경로로 변경했습니다.
=> m_fix : M1 arm64 readline path edit

Makefile, include/minishell.h, src/main.c, src/pipe/parse_commend.c, src/pipe/pipe.h, src/pipe/pipe_main.c
헤더 살짝 수정했는데 머지 안하면 나중에 complicit 날 것 같네요
=> m_fix : modify exec_cmd_main args

src/parse.c, src/parse_split.c
- strtrim whitespace fix
- backslash skip 일단 시작은 했는데 생각보다 골치 아프네요... 높은 확률로 SEGV 되니까 아직은 테스트 할 때 backslash는 쓰지 말아주세요 ㅋㅋ
=> m_fix : trim whitespaces of a complete line & m_feat : skipping backslash draft NOT WORKING YET

src/pipe/breed_process.c, src/pipe/pipe_main.c
놂에 맞출 겸 깔끔하게 정리할 겸 해서 함수좀 정리했읍니다.
exit는 좀 더 연구해보고 구현할 수 있을 것 같습니당. 단순하게 접근하니 가끔 원치 않게 종료되더라구요
낮에 좀 쉴것 같은데 지한님도 쉬엄쉬엄 하세욤 ㅎㅎㅎ;;
=> m_fix : reorganize pipe_main function, fix minor bug on pipe redirection

Makefile, include/parse.h, src/parse/parse.c, src/parse/parse_split.c
/src/parse directory 랑 parse.h 따로 만들고 Makefile 수정했습니다.
=> m_etc : create src/parse directory & src/include directory

Makefile, include/parse.h, src/main.c, src/parse/parse.c, src/parse/parse_split.c, src/parse/parse_utils.c
이제 backslash + chr 도 처리합니다 :D
그리고 몇가지 parse 단계에서 오류 발견해서 수정 했습니다.
코드가 많이 더럽지만... 차차 정리하죠 ㅋㅋㅋ
=> m_feat : backslash skip & QM, BT refinement

Makefile, include/minishell.h, include/parse.h, lib/libft/ft_strtrim.c, src/main.c, src/parse/check_syntax.c, src/parse/parse_main.c, src/parse/parse_split.c, src/parse/sub_env.c, src/parse/utils_main.c
- 환경변수 치환 완성
- pipe/semi-colon syntax error handling - 에러 시 할당 해제 후 cmds == NULL
- 아직 leak check 안 했습니다.
=> ENV var. complete & pipe/semi-colon syntax error check

include/minishell.h, include/parse.h, src/main.c, src/parse/check_syntax.c, src/parse/parse_main.c, src/parse/parse_split.c, src/parse/utils_main.c, src/parse/utils_split.c
leaks & fsanitize 확인했고, 아래 두개 빼면 parsing 완성 됐다고 봐도 될 것 같아요 :D
물론... 아직 모를 일이지만요... ㅋㅋㅋㅋㅋ 터뜨려 주세요 ㅋㅋㅋㅋㅋ
- $? 받아오기
- "'`| 로 internal terminal 열릴 때 SIGINT 들어오면 internal terminal 종료
=> m_fix : leaks & fsanitize checked & backslash jump fixed

include/parse.h, src/parse/parse_main.c
별거 없습니다 ㅋㅋㅋ
그냥 termios.h 함수들 테스트입니다. SIGINT 그 함수들로 해결해보려고 했는데 쉽지 않네요 ㅋㅋ
=> m_etc : termios tests

.vscode/settings.json, include/parse.h, src/main.c, src/parse/parse_main.c
해냈습니다... 드디어!! 이제 진짜 rdr 파싱 할게요 ㅋㅋㅋㅋㅋ
ioctl은 강력하더군요... ioctl cmd로 input queue에 fake input을 넣어서 read 종료시킬 수 있어요!
=> m_fix : internal terminal SIGINT handling done

.gitignore, .vscode/settings.json, README.md
.gitignore update랑 readme ref 하나 추가했어요 ^_^
=> m_etc : README ref & .gitignore update

src/parse/parse_main.c
에... 일단 PR 남발 죄송합니다 하하
norm 맞추다가 double free 되게 해놨더라고요 하하 고쳤습니다 ^_^
=> m_fix : internal prompt sigint handle norm check and double free err

include/pipe.h, src/pipe/parse_commend.c, src/pipe/pipe.h, src/pipe/pipe_main.c, src/pipe/pipe_signal.c
시그널 2줄로 있는걸 한줄로 바꿨는데 저게 맞는지 모르겠네요.
맞겠죠 뭐... ㅎ
pipe_signal.c 파일에 sigint_n_sigquit_handler 함수 체크해주세요 ㅎㅎ; 
근데 함수이름 대박구리네요 으악
=> change signal function. please check it

include/pipe.h, src/pipe/get_params.c, src/pipe/get_rdr_info.c, src/pipe/parse_commend.c, src/pipe/pipe.h, src/pipe/pipe_main.c, src/pipe/rdr_list.c, src/pipe/string_utils.c
리다이렉션 분기 나누는 조건문의 틀만 짜봤는데 if-else문만 30줄이 나오네요?
함수로 나눠서 놂 피해가는건 넘나 쉽지만 이게 맞나 싶네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ으악
=> m_feat : blueprint of redirecting condition-statement

Makefile, include/parse.h, src/main.c, src/parse/parse_main.c, src/parse/parse_split.c, src/parse/split_rdr.c
rdr parsing 아직 미완성입니다. rdr 기호 넣으면 거의 확실하게 SEGV 뜹니다...ㅋㅋㅋ conflict 예방하기 위해 일단 PR 보냅니다.
=> incomplete rdr parsing split

include/pipe.h, src/pipe/ft_atoi_fd.c, src/pipe/pipe.h, src/pipe/rdr_info.c, src/pipe/rdr_list.c, src/pipe/rdr_read.c, src/pipe/rdr_write.c
ㅎㅎ 이제 조건에 맞게 리다이렉션을 잘 연결해주면,,, 어디서 팡팡 터질지 볼 수 있습니다!
=> Parsing rdr_info done

Makefile, include/pipe.h, src/main.c, src/pipe/breed_process.c, src/pipe/connect_pipe.c, src/pipe/file_redirection.c, src/pipe/pipe.h, src/pipe/rdr_info.c, src/pipe/rdr_read_info.c, src/pipe/rdr_write_info.c
컴파일은 가능하게 만들어 뒀는데 작동이 되는진 테스트를 좀 해봐야겠네요.
드디어 최소한의 명령어가 작동하던 1주일 전의 미니쉘로 돌아왔습니다🤣🤣🤣🤣
=> feat : execute respect redirection

Makefile, lib/libft/Makefile
메이크파일을 꾸며보았읍니다... 맘에 안드시면 말해주세요.
참고로 저는 맘에 안듭니다... 뭐 그전보다 오백만배 낫긴 하지만요...
유니크하지 않아... 덜이뻐... 
막 아스키아트도 넣고 기가막히게 멋지게 만들고 싶은데 아이디어도 안떠오르고 기능도 잘 모르겠어서 열받네요 ㅎㅎ;;
입이 떡 벌어지는 아름다운 메이크파일을 만들 아이디어가 있으면 부탁드립니다. 정말로요. 제발.
=> m_feat : customize Makefile

Makefile
zsh에선 멀쩡했지만 저희 소중한 esh에서 makefile의 마지막 출력 라인이 터미널에 남아있어서 수정했습니다
=> m_fix : fixed remainning last line bug

Makefile, include/pipe.h, src/pipe/breed_process.c, src/pipe/file_redirection.c, src/pipe/pipe.h, src/pipe/pipe_signal.c, src/pipe/rdr_info.c, src/pipe/rdr_read_info.c
ㅇㅏ마... 다 될겁니다,,,,,,,, 모르겠네요,,,,,,,,
수많은 리다이렉션의 향연입니다 ㅎㅎ; 어디 버그날지도 모르곘어요 너무 많아서
`<<a <<b <<c <<d` 이런 케이스들이 매번 STDIN으로 리다이렉션을 하면서 입력도 STDIN으로 받는데, bash는 어떻게 하는지 모르겠지만
코드로 짜 보니 처음 `<<a`를 실행하고 나면 stdin이 리다이렉션 되어서 입력을 못받고, 제가 while(1)로 gnl을 쓰는데 stdin이 파일로 바뀌어서 입력을 이상하게 받아 무한루프를 돌고 앉아 있더라구요 하핳
그래서 배쉬에서 255번 파일 디스크립터가 항상 터미널을 가리키고 있다는 점을 활용하여(얘는 리다이렉션 시켜도 안먹고 계속 터미널을 가리키더라구요. 똑같이 구현할까요? 이건 쉽습니다) 255번으로 입력을 받는 방식으로 구현했는데 어떻게 생각하시는지요 ㅎ
그리고 heredoc라는 << 리다이렉션의 임시파일은 .tmp.10000으로 정하고 여러개가 올 수 있으니 ++하다가 20000이 되면 다시 10000부터 시작하는 방식으로 구현했는데 어떤가요? 쉘의 mktemp는 /경   로 /tmp.ran_dom_patton 이런식인데 스택에서 선언한 포인터 주소가 바뀐다는 점을 이용하여 랜덤으로 구현해볼까 했지만 귀찮네요. 나중에 할지도?
암튼 그렇습니다. 코드의 변화는 별로 없네요
+ makefile에서 컴파일할때 디렉토리를 표시하지 않게 바꿨습니다.
=> Redirection done (maybe...)

src/pipe/breed_process.c
아까 오전에 살짝 바꿔둔건데 pr을 안날리고 지한님꺼 머지해서 풀받고 나니 너무 찝찝하네요? 그래서 pr날립니다 ㅎㅎ 머지하게 해주세요
=> m_fix : hotfix : here_doc signal issue

src/pipe/breed_process.c, src/pipe/pipe.h, src/pipe/pipe_main.c, src/pipe/pipe_signal.c
시그널 핸들러를 요리조리 바꿔서 esh> esh> esh> 이게 복사되는건 막았는데, 미니쉘 위 미니쉘에서 sigint 보내면 개행이 한번씩 더 출력되네요
시간이 별로 없어서 급박하게 하다 보니 놓친게 있을 수 있으니 한번 봐주세요 ㅎ
주석처리를 그대로 푸쉬했는데 아직 완벽하게 해결하지 못해서 그대로 남겨뒀습니다
평가하러갑니다~~
=> m_fix : change signal handler but couldn't fix perfectly

include/builtin.h, src/main.c, src/pipe/pipe.h, src/pipe/pipe_main.c
main 살짝 고쳤는데 시험감독이 급 바빠져서 뭐 한게 없네요~~~ 그래도 머지하는게 좋을거같아 pr날립니당
=> m_fix : modify types

Makefile, include/minishell.h, include/parse.h, src/main.c, src/main_signal.c, src/parse/internal_prompt.c, src/parse/parse_main.c
=> m_fix : after EOF SIGINT handling & file clean up

include/exec.h, src/exec/free_structure.c, src/exec/parse_command.c
릭 잡았고 좀 도라이같은 free함수를 만들었는데 필요하세면 쓰세여~~ 
void* 활용 잘하면 참 좋을텐데 말이죠
=> m_fix : fix leaks in exec and add brilliant free func

src/exec/string_utils.c, src/redir/rdr_info.c
ls >"\"" 이때 backslash 스킵에 살짝 문제가 있습니다, 이것 저것 해보고 있는데 아직 못고쳤네요
ls >\"\"\"\"\" 이런건 될겁니당
ls >"\"\"\"\"\"" 이런거 테스트 하다가 #146 을 발견하였읍니다,,
=> m_etc : fix-ing filename bug

src/parse/internal_prompt.c
#146 \\ 이후에 qm 나올 때 issue 해결했습니다.
=> m_fix : too much read fixed when bs followed by qm

src/builtin/chdir.c
에... 다행히 comflict는 안 난 것 같네요 ㅋㅋㅋㅋㅋㅋ 마치 아무 문제 없는 척하기 위해 조그마한 commit PR 보냅니다 ㅋㅋㅋㅋㅋ 😉  원래 이 커밋까지 같이 pr 보내려했는데 ㅋㅋㅋㅋ
=> m_fix: remove unnecessary lines

include/builtin.h, src/exec/exec_main.c, src/exec/execute_builtin.c, src/exec/free_structure.c, src/redir/rdr_info.c, src/redir/rdr_read_info.c, src/redir/rdr_write_info.c
고쳤습니다만 그동한 워낙 바꾼게 많아서 어디서 터질지 모르겠네요🤯🤯🤯
뭐 일단 킵해두고 빌트인에서 fd 복구하는 작업부터 해보겠습니당
=> m_fix : fix segfault when redir to fd

src/redir/file_redirection.c
=> m_fix : fix heredoc redirection file stream

include/exec.h, src/exec/exec_main.c, src/exec/execute_subshell.c, src/exec/waiting.c
포크를  하나 부셨습니다. thanks to @jis-kim
=> m_fix : modify useless fork

include/libft.h, lib/libft/Makefile, lib/libft/ft_strrchrset.c, lib/libft/libft.h, lib/libft/strchrset_skip_bs.c, src/parse/rm_qm_utils.c, src/parse/rm_unnecessary_qm.c, src/parse/split_rdr.c, src/parse/sub_env.c
@yongjulejule 이제 merge 하셔도 됩니다!
1. `ls >""` 고쳤습니다
2. `$(없는 환경변수 명)` ''으로 치환해주는 작업 한 후에 `$` 만 들어와도 ''으로 치환하는 문제 있어서 고쳤습니다.
3. `echo \"test` 고쳤습니다
4. `echo "     $TEST lol $TEST"` 고쳤습니다... (TEST가 export 되지 않았다는 가정하에)
5. quote expand 할 때 `<&`, `>&` 도 인식하게 고쳤습니다!
=> rm_qm & sub_env fix

.github/workflows/build_minishell.yml, .github/workflows/norm.yml, include/exec.h, src/exec/execute_subshell.c, src/exec/parse_command.c
PATH unset 됐을때 bash와 거의 동일하게 작동하게 만들었습니다.
bash 에서 PATH unset하고 커멘드에 Makefile 이딴거 넣으면 makefile 내용을 주르륵 읽는데 execve 특성 상 샤뱅이 없으면 그런짓은 못합니다.
근데 이때 exit status가 2라서 그거라도 맞춰줬습니다.
그리고 깃헙 액션이 pr에서만 작동하도록 수정했습니다. 잘될진 모르겠네요
=> fix segfault when unset PATH

.gitignore, src/parse/check_syntax.c
아주 끔찍한 녀석을 잡았습니다. 건방진녀석 저렇게 숨어있다니
휴 42점 벌었으니까 오늘은 집에 가야겠읍니다 ㅎㅎ
=> m_fix : hotfix!! delete forbidden function

src/exec/get_len.c, src/exec/string_utils.c
이 케이스를 빠뜨렸었네요. double quote 안에서 bs + $ 나올 때도 bs 무시하게 해줬습니다!
=> m_fix : double quote + bs + $ rm bs

src/builtin/echo.c
echo -nnnnn -nnnnnnnn -nnnnnnna -nnnnnn avd 이런거 잘 작동합니다~~
=> m_fix : fix echo when put option insanely

src/exec/parse_command.c
=> m_fix : fix check rdr func 

Makefile, README.md, include/builtin.h, include/exec.h, include/minishell.h, include/redir.h, src/exec/execute_subshell.c
헤더에 필요없는 include 다 지웠고 makefile에 bonus 룰 삭제했습니다
=> fix unused things in header and makefile

include/builtin.h, src/builtin/exit.c, src/main.c, src/utils_main.c
exit 인자 에러시 255로 종료하는데 이때 메크로 설정해줬고
rl_outstream이 루프 안에서 도는게 이상하단 생각이 들어서 밖으로 뺐습니당
=> m_fix : use Macro on exit err and change stream before loop

README.md
리드미 이것 저것 수정했는데 맘에 안드시는 부분 있으면 고쳐주세요~~~
=> 🎉🥳🎊FINISH🎊🥳🎉
